#######################################################################
server:
  port: 8066
  servlet:
    context-path: /edu
    session:
      timeout: 1800     #session有效时间  30分钟

#######################################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                         # 数据库连接池的最小维持连接数
      initial-size: 10                    # 初始化提供的连接数
      max-total: 10                       # 最大的连接数
      max-wait-millis: 200                # 等待连接获取的最大超时时间
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
  # 配置静态资源文件路径
  resources:
    static-locations: classpath:/
  thymeleaf:
    cache: false
  redis:  #redis配置
    port: 6379
    password: yang1997
    host: 192.168.3.175
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: 10000
      shutdown-timeout: 2000


#######################################################################
mybatis:
  config-location: classpath:mybatis-config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yang.edu.entity